//header file
#include <iostream>
// using namespace std; gives access to names for objects and variables from the standard library.
using namespace std;
//interger
int main () 
// to execute the program
{
    string hello ="hello world";
    //single letter
    char grade = 'b';
    //numbers    
    int num1 = 10;
    // true or false
    bool isCodingFun = true;
bool isFishTasty = false;
//word
string name = "JENNYKIM";
// print the program 
//print string variable
cout <<hello <<endl;
cout <<name <<endl;
//print char variables
cout <<"My Grade is " " " <<grade <<endl;
//print number variables
cout << num1 <<endl;
//print bool variables
cout << isCodingFun <<endl;  // Outputs 1 (true)
cout << isFishTasty <<endl;  // Outputs 0 (false)

return 0;
}
